spring.application.name=muttley

spring.datasource.url=jdbc:mysql://localhost:3306/muttleyDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin26

spring.jpa.show-sql=false
spring.mvc.hiddenmethod.filter.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/
server.port=8081